### ISSUE TITLE
Menú principal por consola

### ISSUE THREAD

**Issue by KarolBurbanoN** [KarolBurbanoN/MiniProyecto-1-POE#1]
Crear el menú principal por consola con los siguientes opciones:
- Crear Usuario
- Insertar dinero ahorrado 
- Actualizar dinero ahorrado 
- Eliminar dinero ahorrado 
- Buscar cliente por nombre y ver su ahorro 
- Listar todos los clientes
- Solicitar prestamos
- Solicitar CDT

**Comment by SebastianCR0412** [comment]
Falta poner la opcion de solicitar prestamos y CDT
